name: sell_better
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  
  # Image handling
  image_picker: ^1.0.7
  camera: ^0.10.5+9
  photo_view: ^0.14.0
  image: ^4.1.7
  transparent_image: ^2.0.1
  flutter_cache_manager: ^3.3.1
  
  # Sharing & File management  
  share_plus: ^7.2.2
  path_provider: ^2.1.2
  path: ^1.9.0
  
  # Network
  http: ^1.2.0
  dio: ^5.4.1
  
  # State management & Navigation
  flutter_riverpod: ^2.4.10
  go_router: ^13.2.0
  
  # UI Components
  flutter_slidable: ^3.0.1
  
  # Utilities
  uuid: ^4.3.3
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - lib/prompts/
